PRESETS = {
    "hohle2022": {
        "name": "Hohle et al. 2022 — Gene Center Munich",
        "reference": "doi:10.1038/s41598-022-16978-7",
        "scene": {
            "id": "hohle2022",
            "name": "Hohle et al. 2022",
            "table_width_mm": 600,
            "table_height_mm": 450,
            "grid_spacing_mm": 25,
            "components": [
                {"id": "led-01", "type": "source_led", "position": {"x_mm": 50, "y_mm": 100},
                 "angle_deg": 0, "wavelengths_nm": [405, 470, 528], "fwhm_nm": [6, 9, 15],
                 "label": "LED 3λ"},
                {"id": "bs-01", "type": "beamsplitter", "position": {"x_mm": 200, "y_mm": 100},
                 "angle_deg": 45, "reflectance": 0.5, "label": "BS 50/50"},
                {"id": "obj-01", "type": "objective", "position": {"x_mm": 200, "y_mm": 200},
                 "angle_deg": 90, "na": 0.3, "working_distance_mm": 34.0,
                 "focal_length_mm": 20.0, "label": "LWD 10×"},
                {"id": "cryo-01", "type": "cryo_stage", "position": {"x_mm": 200, "y_mm": 310},
                 "angle_deg": 0, "label": "Estágio criogênico"},
                {"id": "cam-01", "type": "camera", "position": {"x_mm": 300, "y_mm": 100},
                 "angle_deg": 0, "label": "Câmera color"},
            ]
        },
        "wavelengths_nm": [405, 470, 528],
        "fwhm_nm": [6, 9, 15],
        "d_target_nm": 80,
        "source_type": "led",
        "use_kofman_n": True,
    },
    "last2023": {
        "name": "Last et al. 2023 — LUMC Leiden",
        "reference": "doi:10.1016/j.jsb.2023.107965",
        "scene": {
            "id": "last2023",
            "name": "Last et al. 2023",
            "table_width_mm": 600,
            "table_height_mm": 450,
            "grid_spacing_mm": 25,
            "components": [
                {"id": "led-01", "type": "source_led", "position": {"x_mm": 50, "y_mm": 100},
                 "angle_deg": 0, "wavelengths_nm": [405, 470, 528], "fwhm_nm": [6, 9, 15],
                 "label": "LedHUB Omicron"},
                {"id": "dc-01", "type": "dichroic", "position": {"x_mm": 200, "y_mm": 100},
                 "angle_deg": 45, "cutoff_nm": 505, "label": "Dicroico Chroma"},
                {"id": "obj-01", "type": "objective", "position": {"x_mm": 200, "y_mm": 200},
                 "angle_deg": 90, "na": 0.9, "working_distance_mm": 1.0,
                 "label": "Nikon 100×/NA0.9"},
                {"id": "cryo-01", "type": "cryo_stage", "position": {"x_mm": 200, "y_mm": 260},
                 "angle_deg": 0, "label": "Linkam CSM196v3"},
                {"id": "cam-01", "type": "camera", "position": {"x_mm": 300, "y_mm": 100},
                 "angle_deg": 0, "label": "pco.edge 4.2 sCMOS"},
            ]
        },
        "wavelengths_nm": [405, 470, 528],
        "fwhm_nm": [6, 9, 15],
        "d_target_nm": 80,
        "source_type": "led",
        "use_kofman_n": False,
    },
    "lnls_cnpem": {
        "name": "LNLS/CNPEM — SIBIPIRUNA setup",
        "reference": "PIBIC 2024",
        "scene": {
            "id": "lnls_cnpem",
            "name": "LNLS/CNPEM SIBIPIRUNA",
            "table_width_mm": 600,
            "table_height_mm": 450,
            "grid_spacing_mm": 25,
            "components": [
                {"id": "led-01", "type": "source_led", "position": {"x_mm": 50, "y_mm": 100},
                 "angle_deg": 0, "wavelengths_nm": [405, 470, 530], "fwhm_nm": [6, 9, 15],
                 "thorlabs_pn": "LED4D120", "label": "LED4D120"},
                {"id": "bs-01", "type": "beamsplitter", "position": {"x_mm": 200, "y_mm": 100},
                 "angle_deg": 45, "reflectance": 0.5, "thorlabs_pn": "BS013",
                 "label": "BS013 50/50"},
                {"id": "obj-01", "type": "objective", "position": {"x_mm": 200, "y_mm": 200},
                 "angle_deg": 90, "na": 0.3, "working_distance_mm": 34.0,
                 "focal_length_mm": 20.0, "label": "LWD 10×/NA0.3"},
                {"id": "cryo-01", "type": "cryo_stage", "position": {"x_mm": 200, "y_mm": 310},
                 "angle_deg": 0, "label": "Estágio Al + LN₂"},
                {"id": "cam-01", "type": "camera", "position": {"x_mm": 300, "y_mm": 100},
                 "angle_deg": 0, "label": "Câmera color"},
            ]
        },
        "wavelengths_nm": [405, 470, 530],
        "fwhm_nm": [6, 9, 15],
        "d_target_nm": 80,
        "source_type": "led",
        "use_kofman_n": True,
    },
}
